spring:
  r2dbc:
    url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/bookstoredb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  change-log: classpath:db/changelog/db.changelog-master.yaml
  url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/bookstoredb}
  user: ${SPRING_DATASOURCE_USERNAME:postgres}
  password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  enabled: true

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE