spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5430/bookstoredb
    username: user
    password: pwd

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5430/bookstoredb
    user: user
    password: pwd
    enabled: true

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    ROOT: ERROR