spring:
  data:
    mongodb:
      authentication-database: admin
      database: mongodb
      username: root
      password: example
      host: localhost
      port: 27017

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

  logging:
    level:
      com.github.cloudyrock.mongock: debug
      ROOT: info