spring:
  datasource:
    url: jdbc:h2:mem:bookstoredb
    driver-class-name: org.h2.Driver
    username: user
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:h2:mem:bookstoredb
    user: user
    password:
    enabled: true